HW2 Data Wrangling
================
Ronae McLin rkm2147
9/21/2020

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.1     ✓ dplyr   1.0.0
    ## ✓ tidyr   1.1.0     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

# Problem 1

Mr. Trash Wheel data

We will be importing the data, and then follow up by cleaning it.

``` r
trash_df = readxl::read_excel("./trash_wheel.xlsx",                    range = "A2:N408") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

We are next going to read and clean precipitation data for 2017/2018.

``` r
rain_2018 = readxl::read_excel("./trash_wheel.xlsx",                    sheet = "2018 Precipitation",
        skip = 1) %>% 
        janitor::clean_names() %>% 
        drop_na(month) %>% 
        mutate(year = 2018) %>% 
        relocate(year)
  
rain_2017 = readxl::read_excel("./trash_wheel.xlsx",                    sheet = "2017 Precipitation",
        skip = 1) %>% 
        janitor::clean_names() %>% 
        drop_na(month) %>% 
        mutate(year = 2017) %>% 
        relocate(year)
```

Changing the variable of year into a complete month name and then
combining 2017 and 2018 into one table.

``` r
month_df = 
    tibble(
        month = 1:12,
        month_name = month.name
    )

rain_df = bind_rows(rain_2017, rain_2018)

rain_df =
    left_join(rain_df, month_df, by = "month") %>% 
  select(year, total, month_name) %>% 
  relocate(month_name)
```

Summary of Mr. Trash Wheel

``` r
summary(trash_df)
```

    ##     dumpster         month                year     
    ##  Min.   :  1.00   Length:344         Min.   :2014  
    ##  1st Qu.: 86.75   Class :character   1st Qu.:2015  
    ##  Median :172.50   Mode  :character   Median :2017  
    ##  Mean   :172.50                      Mean   :2016  
    ##  3rd Qu.:258.25                      3rd Qu.:2018  
    ##  Max.   :344.00                      Max.   :2019  
    ##       date                      weight_tons    volume_cubic_yards
    ##  Min.   :2014-05-16 00:00:00   Min.   :0.960   Min.   : 7.00     
    ##  1st Qu.:2015-07-05 00:00:00   1st Qu.:2.757   1st Qu.:15.00     
    ##  Median :2017-03-31 00:00:00   Median :3.265   Median :15.00     
    ##  Mean   :2016-12-23 10:57:12   Mean   :3.263   Mean   :15.54     
    ##  3rd Qu.:2018-05-19 18:00:00   3rd Qu.:3.772   3rd Qu.:16.00     
    ##  Max.   :2019-06-17 00:00:00   Max.   :5.620   Max.   :20.00     
    ##  plastic_bottles   polystyrene   cigarette_butts  glass_bottles   
    ##  Min.   : 210.0   Min.   : 320   Min.   :   980   Min.   :  0.00  
    ##  1st Qu.: 957.5   1st Qu.:1065   1st Qu.:  7000   1st Qu.: 10.00  
    ##  Median :1835.0   Median :2075   Median : 19000   Median : 21.50  
    ##  Mean   :1873.2   Mean   :2139   Mean   : 30754   Mean   : 25.36  
    ##  3rd Qu.:2552.5   3rd Qu.:3120   3rd Qu.: 38000   3rd Qu.: 38.00  
    ##  Max.   :5960.0   Max.   :6540   Max.   :310000   Max.   :110.00  
    ##   grocery_bags    chip_bags       sports_balls   homes_powered  
    ##  Min.   :  50   Min.   : 230.0   Min.   : 0.00   Min.   : 0.00  
    ##  1st Qu.: 600   1st Qu.: 977.5   1st Qu.: 5.00   1st Qu.:35.62  
    ##  Median :1050   Median :1630.0   Median : 8.00   Median :51.42  
    ##  Mean   :1311   Mean   :1780.3   Mean   :11.81   Mean   :43.83  
    ##  3rd Qu.:1912   3rd Qu.:2490.0   3rd Qu.:16.00   3rd Qu.:59.50  
    ##  Max.   :3750   Max.   :5085.0   Max.   :56.00   Max.   :93.67

The trash data frame contains information about the Mr.Trash Wheel trash
collector that is located in Baltimore, Maryland. There is a total of
344 rows in the data frame. The total amount of glass bottles collected
by Mr. Trash Wheel so far is 8724 and the total amount of plastic
bottles so far is 6.4436510^{5}. he median number of sports balls in
2017 was 8.

There is a total of 24 rows in the data frame. The total amount of
precipitation in 2018 was 70.33 inches.

# Problem 2

Convert the entry variable from character (YES vs NO) to a logical
variable (the ifelse or recode function may be useful).

Write a short paragraph about this dataset – explain briefly what
variables the dataset contains, describe your data cleaning steps so
far, and give the dimension (rows x columns) of the resulting dataset.
Are these data tidy?

Answer the following questions using these data:

How many distinct stations are there? Note that stations are identified
both by name and by line (e.g. 125th St A/B/C/D; 125st 1; 125st 4/5);
the distinct function may be useful here. How many stations are ADA
compliant? What proportion of station entrances / exits without vending
allow entrance? Reformat data so that route number and route name are
distinct variables. How many distinct stations serve the A train? Of the
stations that serve the A train, how many are ADA compliant?

``` r
transit_df = read_csv("./transit.csv") %>% janitor::clean_names() %>% 
  select(line, station_name,station_latitude, station_longitude,route1:route11, entry, vending,       entrance_type, ada) %>% 
  mutate(entry, YES = "TRUE", NO = "FALSE")
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

# Problem 3

Creating a Final 538 dataset from three sources of information\!

Importing and tidying of pols data

``` r
pols_df = read_csv("./538_data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year","month","day"))
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

``` r
polsmonth_df = 
    tibble(
        month = c("01","02","03","04","05","06","07","08","09","10","11","12"),
        month_name = month.name
    )

pols_df =
    left_join(pols_df, polsmonth_df, by = "month") %>% 
  mutate(
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem",
      prez_gop == 2 ~ "gop",
      )) %>% 

select(year, gov_gop, sen_gop, rep_gop, gov_dem, rep_dem, sen_dem, month_name, president) %>% 
  relocate(year, month_name)
```

Importing and tidying of the snp data

``` r
snp_df = read_csv("./538_data/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month","day","year"))
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

``` r
snpmonth_df = 
    tibble(
        month = c("1","2","3","4","5","6","7","8","9","10","11","12"),
        month_name = month.name
    )

snp_df =
    left_join(snp_df, snpmonth_df, by = "month") %>% 
  select(year, close, month_name) %>% 
  relocate(year, month_name)
```

Importing and tidying of the unemployment data

``` r
unemployment_df = read_csv("./538_data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percentage"
  )
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

``` r
unmonth_df =
  tibble(
    month = c("jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"),
    month_name = month.name
    )

unemployment_df =
    left_join(unemployment_df, unmonth_df, by = "month") %>% 
  select(year, month_name, percentage)
```

Need to merge the three resulting datasets into one using month and
year.

``` r
final538_df = left_join(pols_df, snp_df, by = c("year","month_name")) %>% 
  mutate(year = as.integer(year))

final538_df = left_join(final538_df, unemployment_df, by = c("year","month_name"))
```

Final 538 data

``` r
summary(final538_df)
```

    ##       year       month_name           gov_gop         sen_gop    
    ##  Min.   :1947   Length:822         Min.   :12.00   Min.   :32.0  
    ##  1st Qu.:1964   Class :character   1st Qu.:18.00   1st Qu.:42.0  
    ##  Median :1981   Mode  :character   Median :22.00   Median :46.0  
    ##  Mean   :1981                      Mean   :22.48   Mean   :46.1  
    ##  3rd Qu.:1998                      3rd Qu.:28.00   3rd Qu.:51.0  
    ##  Max.   :2015                      Max.   :34.00   Max.   :56.0  
    ##                                                                  
    ##     rep_gop         gov_dem        rep_dem       sen_dem     
    ##  Min.   :141.0   Min.   :17.0   Min.   :188   Min.   :44.00  
    ##  1st Qu.:176.0   1st Qu.:22.0   1st Qu.:211   1st Qu.:48.00  
    ##  Median :195.0   Median :28.0   Median :250   Median :53.00  
    ##  Mean   :194.9   Mean   :27.2   Mean   :245   Mean   :54.41  
    ##  3rd Qu.:222.0   3rd Qu.:32.0   3rd Qu.:268   3rd Qu.:58.00  
    ##  Max.   :253.0   Max.   :41.0   Max.   :301   Max.   :71.00  
    ##                                                              
    ##   president             close           percentage   
    ##  Length:822         Min.   :  17.05   Min.   : 2.50  
    ##  Class :character   1st Qu.:  83.67   1st Qu.: 4.70  
    ##  Mode  :character   Median : 137.26   Median : 5.60  
    ##                     Mean   : 472.85   Mean   : 5.83  
    ##                     3rd Qu.: 932.06   3rd Qu.: 6.90  
    ##                     Max.   :2107.39   Max.   :10.80  
    ##                     NA's   :36        NA's   :12

The Final 538 dataset combines three data frames containing information
regarding unemployment percentages, national politicians who are
democratic or republican, and the closing values of the S\&P stock
index. There are a total of 822 rows and 11 variables within this set,
with notable variables including “year”, “president”, “close”, and
“percentage”. The information spans between the years 1947, 2015. In
the year 2001 the average unemployment percentage was 4.7416667.
Interestingly so, in the year of 1974, there were 2 gop presidents. The
most recent mean of the closing values for the S\&P stock index was
2070.5649822.
